### ISSUE TITLE
App crashes when trying to change Callout icon

### ISSUE THREAD

**Issue by vtshly** [anyproto/anytype-kotlin#1183]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

The app unexpectedly closes after tapping the Callout icon

https://github.com/anyproto/anytype-kotlin/assets/107392493/a3acd824-c8e6-48a2-86ef-5707567b8235

### Expected Behavior

The icon in the Callout block should be successfully changed

### Steps To Reproduce

1. Create Callout block.
2. Tap on the icon of the Callout block to change it.

### Environment

```markdown
- OS: Android 13
- Version: 0.29.20
```

**Comment by uburoiubu** [comment]
@vtshly, fixed in 0.29.29
