### ISSUE TITLE
Adaptive, Themed Icon for Android 13

### ISSUE THREAD

**Issue by raygervais** [anyproto/anytype-kotlin#236]
**Is your feature request related to a problem? Please describe.**

Firstly, congrats on the open beta! I've been following for a while and jumped into the beta the moment I heard it was announced. Upon installing the app and adding it to my most-used, I noticed the app doesn't-yet implement the [adaptive icon API](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#add_your_adaptive_icon_to_your_app) for those who are on the Material You train -pixel users, really.

**Describe the solution you'd like**

A simplistic implementation of the adaptive icon which supports theming so that it fits with one's home screen if they are using a launcher which supports icon theming.

**Describe alternatives you've considered**
N/A

**Additional context**
I've never implemented adaptive icons myself before, but I'd be open to helping do so as a contributor :)

**Comment by uburoiubu** [comment]
hey, @raygervais, thanks for reporting, we're starting to work on our adaptive icon.

**Comment by paeddi** [comment]
Wow, that was really soon.
I just got the new version with themes icon.
Thank you for your work!

**Comment by uburoiubu** [comment]
done!

**Comment by uburoiubu** [comment]
thanks for opening this issue, now we're happy to close it)
