### ISSUE TITLE
Importing `Experience Template` is broken

### ISSUE THREAD

**Issue by vedxp** [anyproto/anytype-kotlin#754]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Importing templates from Any Experience Gallery doesn't work on Android.

### Expected Behavior

It should copy the template to my vault upon clicking the template link.

### Steps To Reproduce

- Browse the Any Experience Gallery for templates
- Choose any template (eg, [Movie Database](https://gallery.any.coop/Hobbies?experience=movie_database))
- Click on `Open in app`
- AnyType app opens, but nothing happens

### Environment

```markdown
- OS: Android 13
- Version: 0.27.16
```

### Anything else?

>  I have considered creating a pull request with fixes instead of a bug report and want to proceed

Sadly, I won't be able to do a PR for the fix.

**Comment by fuksman** [comment]
Hi @vedxp, installation from the Gallery is currently implemented on Desktop only, we will release it for mobile later.
