### ISSUE TITLE
There should be no bright backgrounds when using dark theme 

### ISSUE THREAD

**Issue by shalva97** [anyproto/anytype-kotlin#852]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Here the first screen when I open the app that has bright gradient background
![Screenshot_20240211-192625_Anytype](https://github.com/anyproto/anytype-kotlin/assets/22417494/e2d5872a-06d1-4ead-99ef-c25c1afeaf7b)

### Expected Behavior

should be something like this
![image](https://github.com/anyproto/anytype-kotlin/assets/22417494/e225d1f6-6751-4057-b82c-ed8241d5db8c)

### Steps To Reproduce

Open the app

### Environment

```markdown
- OS: Android 13
- Version: 0.27.23
```

### Anything else?

Thanks for this nice app

**Comment by konstantiniiv** [comment]
Hello, this functionality is not ready yet, but in the current versions, you can simply choose darker wallpapers in the space settings.

**Comment by shalva97** [comment]
Thanks, it looks just like I want it to
